### ISSUE TITLE
Save sorted json

### ISSUE THREAD

**Issue by mikedepetris** [little-brother/jsontab-wlx#2]
The sorting features on data is perfectly what I need so often. I cannot find a way to save the json with sorted or filtered data, or at least to copy text version of data after sorting, I can only copy cells and rows, not the defining json text.
Would it be possible to:
1. save the json file with actual applied filters and sorting
2. keep filter and sorting when switching from Grid to Text tab view

?
Thanks.

**Comment by little-brother** [comment]
> I cannot find a way to save the json with sorted or filtered data
> 1. save the json file with actual applied filters and sorting

Because there is no such feature. I'll think about what can be done with it. 

> 2. keep filter and sorting when switching from Grid to Text tab view
The filter and sorting are reseted when you switch node in the tree because in most cases old filters/sorters don't have matter.  
I can add a some code to prevent the reset while you're holding `Ctrl` + `Shift`.

**Comment by mikedepetris** [comment]
Anything would be good, 1. or 2. with Ctrl+Shift any of this single things would let me do the main job, of course it would be great to have all the options.
It is a fact there is no other software to easily do the same operations in json !

**Comment by little-brother** [comment]
Both done. But `1.` is implemented with limitation: if a some value is not plain (e.g. object or array) then a result will be contain `[Object]` or `[Array]` instead of this value.

![изображение](https://user-images.githubusercontent.com/20204037/151858274-62193a6f-d24f-45e1-b3f2-d152014029fe.png)

**Comment by mikedepetris** [comment]
Thank you, 2. is ok even if it is not that intuitive, but ok.
I do not know how did you implemented 1., "File --> Save as..." seems to always copy the original file. Can you explain please?

**Comment by little-brother** [comment]
Because TC plugin interface doesn't provide such ability. The top menu is controlled by TC, not by a plugin code. 
Perhaps, it's possible to change it by some system tricks but it's not very easy.

**Comment by mikedepetris** [comment]
Ah ok, let's keep it simple as it is, it's great
