### ISSUE TITLE
Right click on tree (Ieft) panel of the viewer crashes TCM if it's not on a node.

### ISSUE THREAD

**Issue by pplupo** [little-brother/jsontab-wlx#3]
Hi.
If I right-click on any of the green elements, the context menu works properly.
If I right click on the panel directly, not on any nodes (the red area), TCM crashes. It closes immediately.
![image](https://user-images.githubusercontent.com/7476901/205815393-aeed4624-b614-4093-84ce-725566b92bbb.png)

**Comment by pplupo** [comment]
Great! Thanks. :-)

**Comment by little-brother** [comment]
Done.
