### ISSUE TITLE
Some of big jsons open in common Lister view instead jsontab

### ISSUE THREAD

**Issue by ChaosPaladin** [little-brother/jsontab-wlx#4]
![image](https://user-images.githubusercontent.com/10120702/233828097-47c2aeed-9b8d-4f35-b24c-05d9254aa3d6.png)
![image](https://user-images.githubusercontent.com/10120702/233828109-1da6ddc6-30c9-4339-8195-dc7dc0f623b1.png)

**Comment by little-brother** [comment]
Try to increase `max-file-size`-param in ini-file. By default, it's `1000 000` (1MB).

**Comment by ChaosPaladin** [comment]
Yes, that resolve issue
